Taskker/Controllers/AuthController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Taskker.Models;
using Taskker.Models.DAL;
using System.Configuration;
using System.Web.Security;
using System.Collections.Generic;
using System.Web;

namespace Taskker.Controllers
{
    public class AuthController : Controller
    {

        private UnitOfWork unitOfWork;
        public AuthController()
        {
            this.unitOfWork = new UnitOfWork();
        }

        // GET: Auth
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// Crea una cookie de autenticacion en base a un usuario
        /// </summary>
        /// <param name="usuario">Usuario para la cookie</param>
        /// <returns>Cookie de autenticacion</returns>
        private HttpCookie CreateAuthCookie(Usuario usuario)
        {
            FormsAuthentication.SetAuthCookie(usuario.Email, false);
            FormsAuthentication.SetAuthCookie(
                Convert.ToString(usuario.ID),
                false
            );

            /***
             * Creamos el ticket de autenticacion
             * el nombre sera el ID del usuario
             * el tiempo de expiracion esta seteado a 30 minutos
             * Ingresamos tambien los roles del usuario para que puedan ser accedidos por
             * el filtro de autenticacion
             */

            var authTicket = new FormsAuthenticationTicket(
                1,
                usuario.ID.ToString(),
                DateTime.Now,
                DateTime.Now.AddMinutes(30),
                false,
                String.Join(",", usuario.Roles.ToList())
            );

            // Encriptamos y creamos la cookie
            string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
            var authCookie = new HttpCookie(
                FormsAuthentication.FormsCookieName,
                encryptedTicket
            );

            return authCookie;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel _user)
        {
            //_user.Email = "nicolas.a.sandez@gmail.com";
            //_user.Password = "pass123";

            if (!ModelState.IsValid)
                return View(_user);

            // Hasheamos la password para ingresarla a la db
            byte[] hashed_password = Utils.HashPassword(_user.Password);

            // Buscamos el usuario en la base de datos
            Usuario user_logged = unitOfWork.UsuarioRepository.Get(
                u => u.Email == _user.Email && hashed_password == u.EncptPassword).SingleOrDefault();

            if (user_logged == null)
            {
                ModelState.AddModelError("login", "Usuario incorrecto.");
                return View(_user);
            }

            string pictureEncoded = null;

            if (user_logged.EncodedProfilePicture == null)
            {
                pictureEncoded = Utils.EncodePicture(ConfigurationManager.AppSettings["DefaultProfile"]);
            } else
            {
                pictureEncoded = Utils.EncodePictureFromBase64(user_logged.EncodedProfilePicture);
            }

            // Agregamos la cookie a la respuesta
            HttpContext.Response.Cookies.Add(CreateAuthCookie(user_logged));

            UserSession userSession = new UserSession()
            {
                NombreApellido = Utils.Capitalize(user_logged.NombreApellido),
                Email = user_logged.Email,
                EncodedPicture = pictureEncoded,
                ID = user_logged.ID
            };

            Session["UserSession"] = userSession;

            return RedirectToAction("Index", "Browse");

        }

        [HttpGet]
        public ActionResult Logout()
        {
            // Limpiamos los datos de sesion
            Session.Clear();

            // Eliminamos la cookie
            Roles.DeleteCookie();
            
            // Eliminamos el ticket de autenticacion
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegistroModel _user)
        {
            
            // Chequeamos si el modelo es correcto
            if (!ModelState.IsValid)
                return View(_user);

            // Buscamos si el email ya esta registrado
            Usuario found = unitOfWork.UsuarioRepository.Get(u => u.Email == _user.Email).SingleOrDefault();

            if (found != null)
            {
                ModelState.AddModelError("login", "El correo electronico ingresado ya esta en uso.");
                return View(_user);
            }


            Usuario nuevo = new Usuario();
            nuevo.Email = _user.Email;
            // Hasheamos la password para guardarla en la base de datos
            nuevo.EncptPassword = Utils.HashPassword(_user.Password);

            // El rol por defecto siempre sera desarrollador
            Rol defaultRole = unitOfWork.RolRepository.Get(r => r.Nombre == "Desarrollador").SingleOrDefault();

            nuevo.Roles = new List<Rol>() { defaultRole };
            nuevo.Nombre = _user.Nombre;
            nuevo.Apellido = _user.Apellido;
            // Si el usuario no subio una foto entonces se asigna la foto por defecto
            if (_user.Photo == null)
            {
                // Obtenemos el path desde appsettings en web.config
                nuevo.EncodedProfilePicture = Utils.EncodePicture(ConfigurationManager.AppSettings["DefaultProfile"]);
            }
            else
            {
                nuevo.EncodedProfilePicture = Utils.EncodeFromStream(_user.Photo.InputStream);
            }

            // Agregamos el usuario nuevo al contexto
            unitOfWork.UsuarioRepository.Insert(nuevo);

            // Hacemos un commit de los cambios
            unitOfWork.Save();

            HttpContext.Response.Cookies.Add(CreateAuthCookie(nuevo));

            UserSession userSession = new UserSession()
            {
                NombreApellido = nuevo.NombreApellido,
                Email = nuevo.Email,
                EncodedPicture = nuevo.EncodedProfilePicture,
                ID = nuevo.ID
            };

            Session["UserSession"] = userSession;


            return RedirectToAction("Index", "Browse");
        }
    }
}

Taskker/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taskker.Models;
using Taskker.Models.DAL;
using System.Text.Json;
using System.Web.Helpers;

namespace Taskker.Controllers
{
    [Authorize]
    [CustomAuthenticationFilter]
    public class GroupsController : Controller
    {
        private UnitOfWork unitOfWork;

        public GroupsController()
        {
            unitOfWork = new UnitOfWork();
        }

        // GET: Groups
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Join()
        {

            List<Grupo> grupos = unitOfWork.GrupoRepository.Get().ToList();

            ViewData["Grupos"] = grupos;

            return View();
        }

        [HttpPost]
        public ActionResult Join(string nombre)
        {
            UserSession us = (UserSession)Session["UserSession"];

            Usuario found = unitOfWork.UsuarioRepository.Get(_user => _user.Email == us.Email).SingleOrDefault();

            if (found == null)
            {
                return RedirectToAction("Index", "Browse");
            }
            
            Grupo gFound = unitOfWork.GrupoRepository.Get(_grp => _grp.Nombre == nombre).SingleOrDefault();

            if (gFound == null)
            {
                ModelState.AddModelError("Error", "El grupo no existe.");
                return View();
            }

            // Chequemos si el usuario ya esta en el grupo
            if (!gFound.Usuarios.Contains(found))
                gFound.Usuarios.Add(found);

            unitOfWork.Save();

            return RedirectToAction("Index", "Browse");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Accion para eliminar un usuario de un grupo
        /// </summary>
        /// <param name="groupid">ID del grupo</param>
        /// <param name="userid">ID del usuario a eliminar</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult DeleteUserFromGroup(int groupid, int userid)
        {
            Grupo groupFound = unitOfWork.GrupoRepository.GetByID(groupid);
            var user = from u in groupFound.Usuarios
                       where u.ID == userid
                       select u;
            Usuario userToDelete = user.SingleOrDefault();
            if (userToDelete != null)
            {
                groupFound.Usuarios.Remove(userToDelete);

                // Intentamos actualizar el modelo
                if (TryUpdateModel(groupFound, new string[] { "Usuarios" }))
                {
                    unitOfWork.Save();
                }
            }

            return null;
        }

        [HttpPost]
        public ActionResult Create(GrupoModel gm)
        {
            if (String.IsNullOrEmpty(gm.nombre))
            {
                ModelState.AddModelError("Error", "El nombre del grupo no puede estar vacio.");
                return View();
            }

            var grp = from g in unitOfWork.GrupoRepository.Get(gr => gr.Nombre == gm.nombre)
                      select g;

            UserSession us = (UserSession)Session["UserSession"];

            var user = unitOfWork.UsuarioRepository.GetByID(us.ID);

            try
            {
                grp.Single();

                // Ya existe el grupo
                ModelState.AddModelError("Error", "El grupo ya existe.");
                return View();
            }
            catch (InvalidOperationException)
            {
                
                Grupo nuevo = new Grupo
                {
                    Nombre = gm.nombre,
                    UsuarioID = us.ID
                };

                // Agregamos al usuario creador al grupo
                nuevo.Usuarios = new List<Usuario>() { user };

                // Guardamos el grupo
                unitOfWork.GrupoRepository.Insert(nuevo);

                unitOfWork.Save();
            }

            return RedirectToAction("Index", "Browse");
        }

        /// <summary>
        /// Accion para obtener todos los grupos disponibles (solamente los nombres)
        /// en formato json
        /// </summary>
        /// <returns>Json</returns>
        [HttpGet]
        public ActionResult GetGroups()
        {
            List<string> nombresGrupos = new List<string>();

            unitOfWork
                .GrupoRepository
                .Get()
                .ToList()
                .ForEach(g => nombresGrupos.Add(g.Nombre));
            
            // Serializamos la lista con los nombres de grupos
            var json = JsonSerializer.Serialize<List<string>>(nombresGrupos);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Accion para ver los detalles de un grupo
        /// </summary>
        /// <param name="gname"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("GroupDetails/{gname:string}")]
        public ActionResult GroupDetails(string gname)
        {
            var group = from g in unitOfWork.GrupoRepository.Get(_grp => _grp.Nombre == gname)
                        select g;

            Grupo groupFound = group.Single();
            return PartialView("GroupDetails", groupFound);
        }
    }
}

Taskker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)
</head>
<body>

    <main>
        @Scripts.Render("~/lib/materialize/js/materialize.min.js")
        @Styles.Render("~/lib/materialize/css/materialize.min.css")
        @RenderBody()

    </main>

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Contacto</h5>
                    <p class="grey-text text-lighten-4">nicolas.a.sandez@gmail.com</p>
                </div>
                @*<div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Enlaces</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>*@
            </div>
        </div>

        <div class="footer-copyright">
            <div class="container">
                © 2023 Copyright
            </div>
        </div>

    </footer>

</body>
</html>

Taskker/Views/Shared/_Menu.cshtml
@using Taskker.Models;
@using Taskker.Models.DAL;

@{
    var session = Session["UserSession"] as UserSession;
    var email = session.Email;
    var picture = session.EncodedPicture;
    var nombre = session.NombreApellido;
    var gruposNombres = (List<string>)Session["Grupos"];
}

<style>
    .sidenav li a:hover {
        background-color: #d96d6d !important;
        color: white !important;
    }
</style>

<script>
    // Inicializamos el sidenav
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.sidenav');
        M.Sidenav.init(elems, { edge: 'left' });

        var collapsibleElems = document.querySelectorAll('.collapsible');
        M.Collapsible.init(collapsibleElems, {});


        var elemsDropdown = document.querySelectorAll('.dropdown-trigger');
        M.Dropdown.init(elemsDropdown, {});

        $('.btndel-note').on('click', function (element) {
            var nid = element.target.getAttribute('data')
            $.ajax({
                type: "GET",
                url: "/Browse/DeleteNote",
                data: { id: nid },
                success: function (data) {
                    if (data) {
                        $(`#${nid}`).remove()
                    } else {
                        alert("No se pudo eliminar la nota.")
                    }
                }
            })
        })

        $('.btnedit-note').on('click', function (element) {
            debugger;
            var nid = element.target.getAttribute('data');
            var note = $(`.edit-trigger[data=${nid}]`).toArray()[0];
            var noteUpdated = note.textContent;
            $.ajax({
                type: "GET",
                url: "/Browse/UpdateNote",
                data: { id: nid, text: noteUpdated },
                success: function (data) {
                    if (!data) {
                        alert("No se pudo actualizar la nota.")
                    }
                }
            })
        })
    });
</script>

<ul id="slide-out" class="sidenav" style="width: 450px !important">
    <li>
        <div class="user-view">
            <div class="background">
                <img src="@Url.Content("~/images/fondo-rosa.jpg")">
            </div>
            <a href="#user"><img class="circle" src="@picture"></a>
            <a href="#name"><span class="white-text name">@nombre</span></a>
            <a href="#email"><span class="white-text email">@email</span></a>
            <a href="@Url.Action("Logout", "Auth")">Salir</a> | <a href="@Url.Action("Index", "Account")">Perfil</a>
        </div>
    </li>
    <li><a class="waves-effect" href="@Url.Action("Create", "Groups")"><i class="material-icons">group</i>Crear grupo</a></li>
    <li><a class="waves-effect" href="@Url.Action("Join", "Groups")"><i class="material-icons">group_add</i>Unirse</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader" style="color: #d96d6d !important;">Grupos</a></li>
    @{
        foreach (var grupo in gruposNombres)
        {
            <li><a class="waves-effect" href="@Url.Action("Index", "Browse", new { grupo = grupo })">@grupo</a></li>
        }
    }
    <li>
        <!-- Notas -->
        <ul class="collapsible">
            <li>
                <div class="collapsible-header"><i class="material-icons">border_color</i>Notas</div>
                <div class="collapsible-body">
                    <div class="row">
                        @Html.ValidationSummary(false, "", new { @style = "color:red;font-weight:bold" })
                        @using (Html.BeginForm("CreateNote", "Browse", FormMethod.Post, new { @class = "col s12" }))
                        {
                            <div class="row">

                                <div class="input-field col s9">
                                    <textarea id="icon_prefix2" class="materialize-textarea" name="text"></textarea>
                                </div>

                                <div class="col s2">
                                    <button class="btn-small waves-effect waves-light" type="submit" name="action">
                                        <i class="material-icons right">send</i>
                                    </button>
                                </div>
                            </div>
                        }

                    </div>
                    <div class="collection" id="display-notes">
                        @{
                                List<Note> notas = (List<Note>)ViewData["Notes"];
                                foreach (var note in notas ?? Enumerable.Empty<Note>())
                                {
                                <div class="collection-item" id="@note._id">
                                    <div class="row">
                                        <a href="#" data="@note._id" class="edit-trigger" contenteditable="true">@note.text</a>
                                    </div>

                                    <div class="row">
                                        <a href="#" data="@note._id" class="waves-effect waves-light btn-small btndel-note">Eliminar</a>
                                        <a href="#" data="@note._id" class="waves-effect waves-light btn-small btnedit-note">Editar</a>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </li>
        </ul>
    </li>
</ul>